name: Minimum version tests

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:
    branches:
      - main
      - 'stable/**'

jobs:
  tests:
    name: minimum version tests (${{ matrix.os }}, Julia ${{ matrix.julia-version }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    env:
      JULIA_PKG_SERVER_REGISTRY_PREFERENCE: eager
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        julia-version: ['1.10']
    permissions: # needed to allow julia-actions/cache to proactively delete old caches that it has created
      actions: write
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/cache@v3
      - name: Refresh registries
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.Registry.update()
      - name: Install dependencies (minimum versions)
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.resolve()
      - uses: julia-actions/julia-downgrade-compat@v2
        with:
          mode: deps
          julia_version: ${{ matrix.julia-version }}
      - name: Show resolved package versions
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.status(; mode=Pkg.PKGMODE_MANIFEST)
      - name: Assert minimum dependency versions
        shell: julia --color=yes {0}
        run: |
          using Pkg

          expected = Dict(
              "Compat" => v"3.47.0",
              "CEnum" => v"0.5.0",
              "Qiskit_jll" => v"2.2.3",
          )

          deps = Pkg.dependencies()
          for (name, minimum_version) in expected
              package = only(filter(dep -> dep.name == name, values(deps)))
              @assert package.version == minimum_version "$name resolved to $(package.version), expected $minimum_version"
          end
      - uses: julia-actions/julia-buildpkg@v1
      - name: Test package
        shell: julia --project=. --color=yes {0}
        run: |
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
          include("test/runtests.jl")
